In [ ]:
!pip install torch torchvision

In [1]:
import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# PyTorch Start

In [2]:
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [3]:
x = torch.Tensor(2, 3)
print(x)

tensor([[-6.8598e-33,  4.4836e-41,  3.3503e-06],
        [-8.0726e+35, -2.1111e-19,  4.4836e-41]])


In [4]:
y = torch.zeros(2, 3)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.ones(2, 3)
y = torch.ones(2, 3) * 2
y

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [6]:
y[:, 1] = y[:, 1] + 1
print(y)

tensor([[2., 3., 2.],
        [2., 3., 2.]])


In [7]:
x = torch.ones(2, 2) * 2
x.requires_grad_(True)

tensor([[2., 2.],
        [2., 2.]], requires_grad=True)

In [8]:
z = 2 * (x * x) + 5 * x
z.backward(torch.ones(2, 2))
print(x.grad)

tensor([[13., 13.],
        [13., 13.]])


# Neural Network code

In [ ]:
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(28 * 28, 200)
    self.fc2 = nn.Linear(200, 200)
    self.fc3 = nn.Linear(200, 10)

  def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return F.log_softmax(x)


In [ ]:
net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=200, bias=True)
  (fc2): Linear(in_features=200, out_features=200, bias=True)
  (fc3): Linear(in_features=200, out_features=10, bias=True)
)


In [ ]:
learning_rate = 0.01
optimizer = optim.SGD(net.parameters(), lr=learning_rate, momentum=0.9)
criterion = nn.NLLLoss()

In [ ]:
torch.cuda.is_available()

True

# Book Освещая глубокое обучение




## Тензоры

In [10]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [11]:
print(a[1])

float(a[1])

tensor(1.)


1.0

In [12]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [13]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])
img_t

tensor([[[-2.3581, -0.2351,  1.9946, -0.0863,  0.6802],
         [-0.0986, -0.6375, -0.8170,  0.7877, -1.5928],
         [ 1.4119, -0.5023,  0.3483,  2.1388, -2.1272],
         [-0.2401,  0.0674,  0.6736, -0.1713,  0.0980],
         [ 1.5060,  1.3019, -0.3210, -1.4447,  1.1507]],

        [[-0.4647,  0.0714,  2.2810,  2.4788, -0.0547],
         [-0.2543, -1.5016, -0.5547, -1.7507, -2.3842],
         [-0.0094, -1.3857, -0.4768,  0.8078,  1.1344],
         [-0.1176,  0.6372, -0.9512,  0.6118, -0.4491],
         [-0.8001, -0.1972, -0.2147,  0.7817,  0.9047]],

        [[-2.3618,  0.1094,  0.0914, -1.4461, -0.7955],
         [ 0.6398, -0.4306, -1.6422, -0.4464,  1.2773],
         [-1.5201, -2.7828,  0.6010, -0.7349,  0.1072],
         [-0.2351,  0.6460, -0.5724, -0.5377, -0.3811],
         [ 0.0745, -0.8713, -1.2909, -2.0715,  2.1615]]])

In [14]:
batch_t = torch.randn(2, 3, 5, 5)  # форма [батч, каналы, строки, столбцы]
batch_t

tensor([[[[-5.5258e-01,  1.1545e-01, -7.8921e-01, -7.7315e-02,  9.3863e-01],
          [ 1.0047e+00, -1.6170e+00, -1.1907e+00,  5.5407e-01,  5.8535e-01],
          [ 2.1801e-01,  1.7384e-01, -9.3190e-02,  3.6594e-01, -9.3620e-01],
          [-3.1305e-01,  3.3940e-01, -1.3640e+00, -7.1898e-01,  1.1726e+00],
          [-1.3464e+00,  9.8641e-01, -3.2169e-01,  1.4390e+00, -1.2635e-01]],

         [[ 1.5107e+00,  7.2753e-01, -2.2851e+00,  6.5925e-02, -1.3428e+00],
          [ 2.1530e-01,  9.4907e-01,  9.2813e-01,  5.3405e-01,  1.0416e-01],
          [-1.0303e-01, -1.4513e-01, -7.6638e-01,  9.2338e-01,  2.1130e+00],
          [-1.7942e-01, -4.6000e-01,  9.1076e-01,  1.2690e+00, -2.3716e-01],
          [-2.8429e-02,  1.5612e+00,  4.7886e-01,  8.5702e-02,  5.1084e-01]],

         [[ 2.6840e-01, -3.1131e-01, -1.4670e+00, -3.4091e-01,  5.6487e-01],
          [-1.1452e+00,  6.8777e-01, -3.2916e-01, -1.1943e+00,  4.3638e-02],
          [ 7.0454e-01, -4.1617e-01,  5.4068e-01,  2.3303e-01, -6.5166e-

In [15]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [17]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights.shape

torch.Size([3, 1, 1])

In [26]:
img_weights = (img_t * unsqueezed_weights)
img_weights.shape

torch.Size([3, 5, 5])

In [27]:
batch_weights = (batch_t * unsqueezed_weights)
batch_weights.shape

torch.Size([2, 3, 5, 5])

In [25]:
img_gray_weighted = img_weights.sum(-3)
img_gray_weighted.shape

torch.Size([5, 5])

In [21]:
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape

torch.Size([2, 3, 5, 5])

In [23]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
img_gray_weighted_fancy.shape

torch.Size([5, 5])

In [29]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a.stride()
b = a.view(3, 3)
b.stride(), b

((3, 1),
 tensor([[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]))

In [37]:
a.cos()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])